# Generated by Django 2.1.5 on 2019-07-31 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boardgame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('HEAVY', 'استراتژی سنگین'), ('LIGHT', 'استراتژی سبک'), ('FAMILY', 'خانواده و مهمانی'), ('ABSTRACT', 'استراتژی انتزاعی')], max_length=50)),
                ('min_players', models.IntegerField()),
                ('max_players', models.IntegerField()),
                ('best_players', models.IntegerField()),
                ('rate', models.FloatField(default=5, null=True)),
                ('learning_time', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('image_name', models.CharField(default='default.jpg', max_length=500, null=True)),
                ('description', models.TextField()),
                ('bgg_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('ended_date_time', models.DateTimeField(blank=True, null=True)),
                ('is_close', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DeletedItemsInvoiceSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField()),
                ('item_type', models.CharField(choices=[('SHOP', 'Shop Product'), ('MENU', 'Menu Item'), ('GAME', 'Game Item')], max_length=50)),
                ('item_numbers', models.IntegerField()),
                ('message', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_used', models.IntegerField(default=0)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(default='00:00:00', null=True)),
                ('numbers', models.IntegerField()),
                ('points', models.IntegerField(default=0)),
                ('add_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('settlement_type', models.CharField(choices=[('CASH', 'نقدی'), ('CREDIT', 'اعتباری')], max_length=50)),
                ('tax', models.IntegerField()),
                ('discount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceExpenseToService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default='NOT DEFINED', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('invoice_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.InvoiceExpense')),
            ],
        ),
        migrations.CreateModel(
            name='InvoicePurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField()),
                ('settlement_type', models.CharField(choices=[('CASH', 'نقدی'), ('CREDIT', 'اعتباری'), ('AMANi', 'امانی')], max_length=50)),
                ('tax', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('total_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField()),
                ('return_type', models.CharField(choices=[('CUSTOMER_TO_CAFE', 'مشتری به کافه'), ('CAFE_TO_SUPPLIER', 'کافه به تامین\u200cکننده')], max_length=50)),
                ('buy_price', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('numbers', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField()),
                ('settle_time', models.DateTimeField(blank=True, null=True)),
                ('cash', models.IntegerField(default=0)),
                ('pos', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('employee_discount', models.IntegerField(default=0)),
                ('tax', models.IntegerField(default=0)),
                ('tip', models.IntegerField(default=0)),
                ('settlement_type', models.CharField(choices=[('BANK_CARD', 'کارت بانکی'), ('CASH', 'نقدی')], default='CASH', max_length=50)),
                ('guest_numbers', models.IntegerField()),
                ('is_settled', models.IntegerField(default=0)),
                ('total_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceSettlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField()),
                ('payment_amount', models.IntegerField()),
                ('tax', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InvoicesSalesToGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.Game')),
                ('invoice_sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.InvoiceSales')),
            ],
        ),
        migrations.CreateModel(
            name='InvoicesSalesToMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=60)),
                ('is_print', models.SmallIntegerField(default=0)),
                ('invoice_sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.InvoiceSales')),
            ],
        ),
        migrations.CreateModel(
            name='InvoicesSalesToShopProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=60)),
                ('invoice_sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.InvoiceSales')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unit', models.CharField(choices=[('NOT_DEFINED', 'تعریف نشده'), ('KG', 'کیلوگرم'), ('NUMBER', 'عدد'), ('BOX', 'بسته')], default='NOT_DEFINED', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialToStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.Material')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=20)),
                ('credit', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=15)),
                ('intro', models.CharField(choices=[('search', 'جست\u200cوجوی اینترنت'), ('friends', 'معرفی دوستان'), ('instagram', 'اینستاگرام'), ('roomiz', 'سایت رومیز'), ('events', 'شرکت در رویدادها'), ('other', 'سایر')], default='other', max_length=50)),
                ('year_of_birth', models.IntegerField()),
                ('month_of_birth', models.IntegerField()),
                ('day_of_birth', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('kind', models.CharField(choices=[('KITCHEN', 'آشپزخانه'), ('BAR', 'بار')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.CharField(blank=True, max_length=30, null=True)),
                ('is_delete', models.SmallIntegerField(default=0)),
                ('menu_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounti.MenuCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrinterToCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounti.MenuCategory')),
                ('printer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounti.Printer')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseToMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_unit_price', models.IntegerField()),
                ('unit_numbers', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('invoice_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.InvoicePurchase')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.Material')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseToShopProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_unit_price', models.IntegerField()),
                ('unit_numbers', models.IntegerField()),
                ('buy_numbers', models.IntegerField(default=0)),
                ('sale_price', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('invoice_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.InvoicePurchase')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('numbers', models.IntegerField()),
                ('reserve_date', models.DateTimeField(blank=True, null=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('reserve_state', models.CharField(choices=[('waiting', 'waiting'), ('arrived', 'arrived'), ('walked', 'walked')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReserveToTables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.Reservation')),
            ],
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('real_numbers', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockToBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=30)),
                ('salesman_name', models.CharField(max_length=50)),
                ('salesman_phone', models.CharField(max_length=50)),
                ('last_pay', models.DateField(blank=True, null=True)),
                ('last_buy', models.DateField(blank=True, null=True)),
                ('last_expense', models.DateField(blank=True, null=True)),
                ('last_return', models.DateField(blank=True, null=True)),
                ('remainder', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=30)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.Supplier')),
            ],
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='username',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='branch',
            name='end_working_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='start_working_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_card_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='card_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='father_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='home_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='employee',
            name='membership_card_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='national_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='shaba_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stocktobranch',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounti.Branch'),
        ),
        migrations.AddField(
            model_name='stocktobranch',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounti.Stock'),
        ),
        migrations.AddField(
            model_name='reservetotables',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.Table'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounti.Branch'),
        ),
        migrations.AddField(
            model_name='purchasetoshopproduct',
            name='shop_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.ShopProduct'),
        ),
        migrations.AddField(
            model_name='materialtostock',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.Stock'),
        ),
        migrations.AddField(
            model_name='invoicessalestoshopproducts',
            name='shop_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.ShopProduct'),
        ),
        migrations.AddField(
            model_name='invoicessalestomenuitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.MenuItem'),
        ),
        migrations.AddField(
            model_name='invoicesettlement',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.Branch'),
        ),
        migrations.AddField(
            model_name='invoicesettlement',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.Supplier'),
        ),
        migrations.AddField(
            model_name='invoicesales',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.Branch'),
        ),
        migrations.AddField(
            model_name='invoicesales',
            name='cash_desk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounti.Cash'),
        ),
        migrations.AddField(
            model_name='invoicesales',
            name='member',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounti.Member'),
        ),
        migrations.AddField(
            model_name='invoicesales',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.Table'),
        ),
        migrations.AddField(
            model_name='invoicereturn',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.Branch'),
        ),
        migrations.AddField(
            model_name='invoicereturn',
            name='shop_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.ShopProduct'),
        ),
        migrations.AddField(
            model_name='invoicereturn',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.Supplier'),
        ),
        migrations.AddField(
            model_name='invoicepurchase',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.Branch'),
        ),
        migrations.AddField(
            model_name='invoicepurchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.Supplier'),
        ),
        migrations.AddField(
            model_name='invoiceexpense',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.Branch'),
        ),
        migrations.AddField(
            model_name='invoiceexpense',
            name='expense_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounti.ExpenseCategory'),
        ),
        migrations.AddField(
            model_name='invoiceexpense',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.Supplier'),
        ),
        migrations.AddField(
            model_name='game',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.Member'),
        ),
        migrations.AddField(
            model_name='deleteditemsinvoicesales',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounti.Employee'),
        ),
        migrations.AddField(
            model_name='deleteditemsinvoicesales',
            name='invoice_sales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounti.InvoiceSales'),
        ),
        migrations.AddField(
            model_name='cash',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.Branch'),
        ),
        migrations.AddField(
            model_name='cash',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounti.Employee'),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounti.Branch'),
        ),
    ]
