# Generated by Django 2.1.5 on 2019-07-31 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='MenuItem',
            name='is_delete',
            field=models.SmallIntegerField(default=0),
        ),
    ]
