# Generated by Django 2.1.5 on 2019-01-28 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounti', '0002_employee_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='username',
            new_name='USERNAME_FIELD',
        ),
    ]
