# Generated by Django 2.1.5 on 2019-01-28 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounti', '0003_auto_20190128_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='USERNAME_FIELD',
            new_name='username',
        ),
    ]
