# Generated by Django 2.1.5 on 2019-02-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounti', '0004_auto_20190128_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='username',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='employee',
            name='card_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
