# Generated by Django 2.1.5 on 2019-02-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounti', '0006_auto_20190209_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boardgame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('min_players', models.IntegerField()),
                ('max_players', models.IntegerField()),
                ('best_players', models.IntegerField()),
                ('rate', models.FloatField(default=5, null=True)),
                ('learning_time', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('bgg_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=20)),
                ('credit', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=15)),
                ('intro', models.CharField(choices=[('search', 'جست\u200cوجوی اینترنت'), ('friends', 'معرفی دوستان'), ('instagram', 'اینستاگرام'), ('roomiz', 'سایت رومیز'), ('events', 'شرکت در رویدادها'), ('other', 'سایر')], default='other', max_length=50)),
                ('year_of_birth', models.IntegerField()),
                ('month_of_birth', models.IntegerField()),
                ('day_of_birth', models.IntegerField()),
            ],
        ),
    ]
