# Generated by Django 2.1.5 on 2019-02-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounti', '0007_boardgame_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='category',
            field=models.CharField(choices=[('HEAVY', 'Heavy Strategy'), ('LIGHT', 'Light Strategy'), ('FAMILY', 'Family and Party'), ('ABSTRACT', 'Abstract Strategy')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
