# Generated by Django 2.1.5 on 2019-02-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounti', '0009_boardgame_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='category',
            field=models.CharField(choices=[('HEAVY', 'استراتژی سنگین'), ('LIGHT', 'استراتژی سبک'), ('FAMILY', 'خانواده و مهمانی'), ('ABSTRACT', 'استراتژی انتزاعی')], max_length=50),
        ),
    ]
