# Generated by Django 2.1.5 on 2019-02-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounti', '0010_auto_20190216_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='image_name',
            field=models.CharField(default='default.jpg', max_length=500, null=True),
        ),
    ]
