# Generated by Django 2.1.5 on 2019-02-22 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounti', '0011_boardgame_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_used', models.IntegerField(default=0)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(default='00:00:00', null=True)),
                ('numbers', models.IntegerField()),
                ('points', models.IntegerField()),
                ('add_date', models.DateField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.Member')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField()),
                ('discount', models.IntegerField()),
                ('employee_discount', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('tip', models.IntegerField()),
                ('settlement_type', models.CharField(choices=[('BANK_CARD', 'کارت بانکی'), ('CASH', 'نقدی')], default='CASH', max_length=50)),
                ('guest_numbers', models.IntegerField()),
                ('is_settled', models.IntegerField(default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.Member')),
            ],
        ),
        migrations.CreateModel(
            name='InvoicesSalesToGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.Game')),
                ('invoice_sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.InvoiceSales')),
            ],
        ),
        migrations.CreateModel(
            name='InvoicesSalesToMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.InvoiceSales')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.MenuItem')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
