# Generated by Django 2.1.5 on 2019-02-26 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounti', '0012_game_invoicesales_invoicessalestogame_invoicessalestomenuitem_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesales',
            name='branch',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounti.Branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicesales',
            name='table',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounti.Table'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicessalestomenuitem',
            name='is_print',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoicessalestomenuitem',
            name='numbers',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoicesales',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoicesales',
            name='employee_discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoicesales',
            name='member',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounti.Member'),
        ),
        migrations.AlterField(
            model_name='invoicesales',
            name='tax',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoicesales',
            name='tip',
            field=models.IntegerField(default=0),
        ),
    ]
