# Generated by Django 2.1.5 on 2019-03-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounti', '0013_auto_20190226_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesales',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
