# Generated by Django 2.1.5 on 2019-03-17 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounti', '0015_invoicesales_settle_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='menucategory',
            name='kind',
            field=models.CharField(choices=[('KITCHEN', 'آشپزخانه'), ('BAR', 'بار')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menucategory',
            name='printer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounti.Printer'),
        ),
    ]
