# Generated by Django 2.1.5 on 2019-03-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounti', '0016_auto_20190317_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicessalestomenuitem',
            name='description',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
