# Generated by Django 2.1.5 on 2019-03-24 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounti', '0017_invoicessalestomenuitem_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('settlement_type', models.CharField(choices=[('CASH', 'نقدی'), ('CREDIT', 'اعتباری')], max_length=50)),
                ('tax', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='InvoicePurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField()),
                ('base_unit_price', models.IntegerField()),
                ('unit_numbers', models.IntegerField()),
                ('sale_price', models.IntegerField()),
                ('settlement_type', models.CharField(choices=[('CASH', 'نقدی'), ('CREDIT', 'اعتباری'), ('AMANi', 'امانی')], max_length=50)),
                ('tax', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceSettlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unit', models.CharField(choices=[('KG', 'کیلوگرم'), ('NUMBER', 'عدد'), ('BOX', 'بسته')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialToStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.Material')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('real_numbers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=30)),
                ('salesman_name', models.CharField(max_length=50)),
                ('salesman_phone', models.CharField(max_length=50)),
                ('last_pay', models.DateField(blank=True)),
                ('remainder', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=30)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.Supplier')),
            ],
        ),
        migrations.AddField(
            model_name='invoicesettlement',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.Supplier'),
        ),
        migrations.AddField(
            model_name='invoicepurchase',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.Material'),
        ),
        migrations.AddField(
            model_name='invoiceexpense',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.Service'),
        ),
    ]
