# Generated by Django 2.1.5 on 2019-03-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounti', '0018_auto_20190324_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='last_pay',
            field=models.DateField(blank=True, null=True),
        ),
    ]
