# Generated by Django 2.1.5 on 2019-03-25 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounti', '0019_auto_20190324_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseToMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_unit_price', models.IntegerField()),
                ('unit_numbers', models.IntegerField()),
                ('sale_price', models.IntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.Material')),
            ],
        ),
        migrations.RemoveField(
            model_name='invoicepurchase',
            name='base_unit_price',
        ),
        migrations.RemoveField(
            model_name='invoicepurchase',
            name='material',
        ),
        migrations.RemoveField(
            model_name='invoicepurchase',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='invoicepurchase',
            name='unit_numbers',
        ),
    ]
