# Generated by Django 2.1.5 on 2019-03-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounti', '0020_auto_20190325_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepurchase',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(choices=[('NOT_DEFINED', 'تعریف نشده'), ('KG', 'کیلوگرم'), ('NUMBER', 'عدد'), ('BOX', 'بسته')], default='NOT_DEFINED', max_length=30),
        ),
    ]
