# Generated by Django 2.1.5 on 2019-03-26 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounti', '0021_auto_20190325_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseToShopProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_unit_price', models.IntegerField()),
                ('unit_numbers', models.IntegerField()),
                ('sale_price', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='purchasetomaterial',
            name='sale_price',
        ),
        migrations.AddField(
            model_name='invoicepurchase',
            name='supplier',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounti.Supplier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasetomaterial',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasetomaterial',
            name='invoice_purchase',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounti.InvoicePurchase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasetoshopproduct',
            name='invoice_purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.InvoicePurchase'),
        ),
        migrations.AddField(
            model_name='purchasetoshopproduct',
            name='shop_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.ShopProduct'),
        ),
    ]
