# Generated by Django 2.1.5 on 2019-03-26 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounti', '0022_auto_20190326_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceexpense',
            name='service',
        ),
        migrations.AddField(
            model_name='invoiceexpense',
            name='service_name',
            field=models.CharField(default='NOT DEFINED', max_length=50),
        ),
        migrations.AddField(
            model_name='invoiceexpense',
            name='supplier',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounti.Supplier'),
        ),
        migrations.AddField(
            model_name='invoicesettlement',
            name='branch',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounti.Branch'),
        ),
        migrations.AddField(
            model_name='invoicesettlement',
            name='created_time',
            field=models.DateTimeField(default='1990-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoiceexpense',
            name='branch',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounti.Branch'),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
