# Generated by Django 2.1.5 on 2019-03-26 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounti', '0023_auto_20190326_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceexpense',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.Branch'),
        ),
        migrations.AlterField(
            model_name='invoiceexpense',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.Supplier'),
        ),
        migrations.AlterField(
            model_name='invoicesettlement',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.Branch'),
        ),
    ]
