# Generated by Django 2.1.5 on 2019-04-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounti', '0024_auto_20190326_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='last_buy',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='last_expense',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='last_return',
            field=models.DateField(blank=True, null=True),
        ),
    ]
