# Generated by Django 2.1.5 on 2019-04-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounti', '0025_auto_20190404_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesettlement',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoicesettlement',
            name='tax',
            field=models.IntegerField(default=0),
        ),
    ]
