# Generated by Django 2.1.5 on 2019-04-04 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounti', '0026_auto_20190404_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicesSalesToShopProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=60)),
                ('invoice_sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.InvoiceSales')),
                ('shop_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.ShopProduct')),
            ],
        ),
    ]
