# Generated by Django 2.1.5 on 2019-04-11 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounti', '0028_invoicereturn'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedItemsInvoiceSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField()),
                ('item_type', models.CharField(choices=[('SHOP', 'Shop Product'), ('MENU', 'Menu Item'), ('GAME', 'Game Item')], max_length=50)),
                ('item_numbers', models.IntegerField()),
                ('message', models.CharField(max_length=255)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounti.Employee')),
                ('invoice_sales', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounti.InvoiceSales')),
            ],
        ),
    ]
