# Generated by Django 2.1.5 on 2019-04-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounti', '0029_deleteditemsinvoicesales'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesales',
            name='cash',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoicesales',
            name='pos',
            field=models.IntegerField(default=0),
        ),
    ]
