# Generated by Django 2.1.5 on 2019-05-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounti', '0030_auto_20190419_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasetoshopproduct',
            name='buy_numbers',
            field=models.IntegerField(default=0),
        ),
    ]
