# Generated by Django 2.1.5 on 2019-05-13 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounti', '0031_purchasetoshopproduct_buy_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterToCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='printer',
        ),
        migrations.AddField(
            model_name='printertocategory',
            name='menu_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounti.MenuCategory'),
        ),
        migrations.AddField(
            model_name='printertocategory',
            name='printer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounti.Printer'),
        ),
    ]
