# Generated by Django 2.1.5 on 2019-05-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounti', '0032_auto_20190513_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='membership_card_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
