# Generated by Django 2.1.5 on 2019-05-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounti', '0035_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reserve_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
