# Generated by Django 2.1.5 on 2019-05-19 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounti', '0036_auto_20190519_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounti.Branch'),
        ),
    ]
