# Generated by Django 2.1.5 on 2019-05-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounti', '0038_reservation_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.CharField(default='waiting', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='reserve_state',
            field=models.CharField(choices=[('waiting', 'waiting'), ('arrived', 'arrived'), ('walked', 'walked')], default='waiting', max_length=50),
            preserve_default=False,
        ),
    ]
