# Generated by Django 2.1.5 on 2019-05-21 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounti', '0039_auto_20190521_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveToTables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='table',
        ),
        migrations.AddField(
            model_name='reservetotables',
            name='reserve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.Reservation'),
        ),
        migrations.AddField(
            model_name='reservetotables',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.Table'),
        ),
    ]
