# Generated by Django 2.1.5 on 2019-06-16 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounti', '0040_auto_20190521_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_close', models.SmallIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.Branch')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounti.Employee')),
            ],
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='real_numbers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoicesales',
            name='cash_desk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounti.Cash'),
        ),
    ]
