# Generated by Django 2.1.5 on 2019-06-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounti', '0041_auto_20190616_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='ended_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
