# Generated by Django 2.1.5 on 2019-06-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounti', '0043_auto_20190630_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
