# Generated by Django 2.1.5 on 2019-07-02 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounti', '0045_auto_20190630_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceExpenseToService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default='NOT DEFINED', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='invoiceexpense',
            name='description',
        ),
        migrations.RemoveField(
            model_name='invoiceexpense',
            name='service_name',
        ),
        migrations.AddField(
            model_name='invoiceexpensetoservice',
            name='invoice_expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounti.InvoiceExpense'),
        ),
    ]
