# Generated by Django 2.1.5 on 2019-07-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounti', '0046_auto_20190702_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceexpensetoservice',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
