# Generated by Django 2.1.5 on 2019-07-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounti', '0047_invoiceexpensetoservice_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_delete',
            field=models.SmallIntegerField(default=0),
        ),
    ]
